### ISSUE TITLE
Exceptions when loading plugin on cluster

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-monitoring-plugin#198]
Immediately after loading the plugin on Openfire 4.7.0-SNAPSHOT (that holds the clustering reimplementation), this is being logged.

```2021.10.27 16:13:19 ERROR [hz.openfire.generic-operation.thread-0]: com.hazelcast.executor.impl.operations.MemberCallableTaskOperation - [172.31.25.193]:5701 [openfire] [3.12.5] java.lang.ClassNotFoundException: org.jivesoftware.openfire.reporting.stats.GetStatistics
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: org.jivesoftware.openfire.reporting.stats.GetStatistics
        at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:88) ~[hazelcast-3.12.5.jar!/:?]
        at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:77) ~[hazelcast-3.12.5.jar!/:?]
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.12.5.jar!/:?]
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187) ~[hazelcast-3.12.5.jar!/:?]
        at com.hazelcast.executor.impl.operations.AbstractCallableTaskOperation$OffloadImpl.loadCallable(AbstractCallableTaskOperation.java:106) ~[hazelcast-3.12.5.jar!/:?]
        at com.hazelcast.executor.impl.operations.AbstractCallableTaskOperation$OffloadImpl.start(AbstractCallableTaskOperation.java:98) ~[hazelcast-3.12.5.jar!/:?]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:224) [hazelcast-3.12.5.jar!/:?]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199) [hazelcast-3.12.5.jar!/:?]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416) [hazelcast-3.12.5.jar!/:?]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153) [hazelcast-3.12.5.jar!/:?]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123) [hazelcast-3.12.5.jar!/:?]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110) [hazelcast-3.12.5.jar!/:?]
Caused by: java.lang.ClassNotFoundException: org.jivesoftware.openfire.reporting.stats.GetStatistics
        at org.jivesoftware.openfire.plugin.util.cache.ClusterClassLoader.lambda$loadClass$2(ClusterClassLoader.java:94) ~[hazelcast-2.6.0-SNAPSHOT.jar!/:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_302]
        at org.jivesoftware.openfire.plugin.util.cache.ClusterClassLoader.loadClass(ClusterClassLoader.java:94) ~[hazelcast-2.6.0-SNAPSHOT.jar!/:?]
        at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:288) ~[hazelcast-3.12.5.jar!/:?]
        at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:252) ~[hazelcast-3.12.5.jar!/:?]
        at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:699) ~[hazelcast-3.12.5.jar!/:?]
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1985) ~[?:1.8.0_302]
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1849) ~[?:1.8.0_302]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2159) ~[?:1.8.0_302]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1666) ~[?:1.8.0_302]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2404) ~[?:1.8.0_302]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2328) ~[?:1.8.0_302]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2186) ~[?:1.8.0_302]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1666) ~[?:1.8.0_302]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:502) ~[?:1.8.0_302]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:460) ~[?:1.8.0_302]
        at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:84) ~[hazelcast-3.12.5.jar!/:?]
        ... 11 more

**Comment by evdherberg** [comment]
I have tried and managed to reproduce this issue, but only when the plugin was not installed on one of the nodes. When the plugin is present on all cluster nodes the issue does not seem to occur.

So probably this issue can just be closed. Or maybe some sort of detection mechanism could be designed, to inform admins of improper configuration. But that would be quite a lot of work for something that will normally never occur and doesn't crash the cluster if it does.

**Comment by Fishbowler** [comment]
An Openfire issue exists for this already, I'm sure, where we wanted to alert admins to inconsistent plugin installations (either missing or version mismatch)

**Comment by guusdk** [comment]
Closing this as won't-fix for now.
