### ISSUE TITLE
Gajim not able to get archived messages since 4.3.0 update

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-monitoring-plugin#27]
User reports that Gajim client can't retrieve new history messages from the archive since 4.3.0 update. As reported it was the same with 4.3.0 and 1.6.2 version of plugin. And it was working ok with 4.2.3.

1.7.0 update of the plugin fixed issues in Conversations and this client can retrieve new messages, but Gajim can't.

**Comment by wrooot** [comment]
![image](https://user-images.githubusercontent.com/7195609/51379607-84a3c080-1b18-11e9-9bfd-40c00f7023bc.png)

**Comment by wrooot** [comment]
![image](https://user-images.githubusercontent.com/7195609/51379647-8ec5bf00-1b18-11e9-8a4b-a6a05d246819.png)

**Comment by wrooot** [comment]
this string from debug window:
18.01.2019 12:45:07 (W) gajim.c.m.archiving: Message from invalid archive <message xmlns="jabber:client" to="vladimir@softjoys.pro/Gajim.Home"><result xmlns="urn:xmpp:mam:1" queryid="c0d4d0ba-2046-4abb-8139-e4a0fb2fc7b9" id="228159"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2019-01-14T10:01:46.065Z" /><message xmlns="jabber:client" to="vm@softjoys.pro/gajim.WFFZALQC" type="groupchat" id="bca999f7-6941-4f76-b989-fcdc4378ed7b" from="techsup@conference.softjoys.pro/vladimir"><body>????????? ? ?????????????? ?????.. ?????????, ???????, ???????? https://www.igniterealtime.org/projects/openfire/plugins/1.7.0/monitoring/changelog.html</body><origin-id xmlns="urn:xmpp:sid:0" id="bca999f7-6941-4f76-b989-fcdc4378ed7b" /><active xmlns="http://jabber.org/protocol/chatstates" /></message></forwarded></result></message>
18.01.2019 12:45:07 (W) gajim.c.m.archiving: Message from invalid archive <message xmlns="jabber:client" to="vladimir@softjoys.pro/Gajim.Home"><result xmlns="urn:xmpp:mam:1" queryid="c0d4d0ba-2046-4abb-8139-e4a0fb2fc7b9" id="228160"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2019-01-14T10:02:00.138Z" /><message xmlns="jabber:client" to="vm@softjoys.pro/gajim.WFFZALQC" type="groupchat" id="39e3160a-b6c5-45a9-a83a-3349f62cdb1a" from="techsup@conference.softjoys.pro/vladimir"><body>?? ???? ??????? ??  ????. ??????????, ???? ?????? ?? ?????? ????????????</body><origin-id xmlns="urn:xmpp:sid:0" id="39e3160a-b6c5-45a9-a83a-3349f62cdb1a" /><active xmlns="http://jabber.org/protocol/chatstates" /></message></forwarded></result></message>

**Comment by wrooot** [comment]
`18.01.2019 12:45:07 (W) gajim.c.m.archiving: Message from invalid archive <message xmlns="jabber:client" to="vladimir@softjoys.pro/Gajim.Home"><result xmlns="urn:xmpp:mam:1" queryid="c0d4d0ba-2046-4abb-8139-e4a0fb2fc7b9" id="228159"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2019-01-14T10:01:46.065Z" /><message xmlns="jabber:client" to="vm@softjoys.pro/gajim.WFFZALQC" type="groupchat" id="bca999f7-6941-4f76-b989-fcdc4378ed7b" from="techsup@conference.softjoys.pro/vladimir"><body>????????? ? ?????????????? ?????.. ?????????, ???????, ???????? https://www.igniterealtime.org/projects/openfire/plugins/1.7.0/monitoring/changelog.html</body><origin-id xmlns="urn:xmpp:sid:0" id="bca999f7-6941-4f76-b989-fcdc4378ed7b" /><active xmlns="http://jabber.org/protocol/chatstates" /></message></forwarded></result></message>
18.01.2019 12:45:07 (W) gajim.c.m.archiving: Message from invalid archive <message xmlns="jabber:client" to="vladimir@softjoys.pro/Gajim.Home"><result xmlns="urn:xmpp:mam:1" queryid="c0d4d0ba-2046-4abb-8139-e4a0fb2fc7b9" id="228160"><forwarded xmlns="urn:xmpp:forward:0"><delay xmlns="urn:xmpp:delay" stamp="2019-01-14T10:02:00.138Z" /><message xmlns="jabber:client" to="vm@softjoys.pro/gajim.WFFZALQC" type="groupchat" id="39e3160a-b6c5-45a9-a83a-3349f62cdb1a" from="techsup@conference.softjoys.pro/vladimir"><body>?? ???? ??????? ??  ????. ??????????, ???? ?????? ?? ?????? ????????????</body><origin-id xmlns="urn:xmpp:sid:0" id="39e3160a-b6c5-45a9-a83a-3349f62cdb1a" /><active xmlns="http://jabber.org/protocol/chatstates" /></message></forwarded></result></message>
(12:00) vladimir: and text of Gajim error:
(12:00) vladimir: ## Versions
- OS: Windows 8.1
- GTK+ Version: 3.24.1
- PyGObject Version: 3.30.4
- python-nbxmpp Version: 0.6.9
- Gajim Version: 1.1.2
## Traceback
```
Traceback (most recent call last):
  File "C:/msys64/home/appveyor/gajim/win/_build_root/mingw64/lib/python3.7/site-packages/gajim/gui_interface.py", line 2251, in process_connections
  File "C:/msys64/home/appveyor/gajim/win/_build_root/mingw64/lib/python3.7/site-packages/nbxmpp/idlequeue.py", line 518, in process
  File "C:/msys64/home/appveyor/gajim/win/_build_root/mingw64/lib/python3.7/site-packages/nbxmpp/transports_nb.py", line 451, in pollin
  File "C:/msys64/home/appveyor/gajim/win/_build_root/mingw64/lib/python3.7/site-packages/nbxmpp/transports_nb.py", line 676, in _do_receive
  File "C:/msys64/home/appveyor/gajim/win/_build_root/mingw64/lib/python3.7/site-packages/nbxmpp/transports_nb.py", line 690, in _on_receive
  File "C:/msys64/home/appveyor/gajim/win/_build_root/mingw64/lib/python3.7/site-packages/nbxmpp/dispatcher_nb.py", line 535, in _WaitForData
  File "C:/msys64/home/appveyor/gajim/win/_build_root/mingw64/lib/python3.7/site-packages/gajim/common/modules/mam.py", line 466, in _result_finished
  File "C:/msys64/home/appveyor/gajim/win/_build_root/mingw64/lib/python3.7/site-packages/gajim/common/logger.py", line 1435, in set_archive_infos
  File "C:/msys64/home/appveyor/gajim/win/_build_root/mingw64/lib/python3.7/site-packages/gajim/common/logger.py", line 436, in get_jid_id
ValueError: Unable to insert new JID because type is missing`

**Comment by wrooot** [comment]
[logs.txt](https://github.com/igniterealtime/openfire-monitoring-plugin/files/2772472/logs.txt)
