### ISSUE TITLE
MAM Before/After returns error

### ISSUE THREAD

**Issue by munkhbayar-gtk** [igniterealtime/openfire-monitoring-plugin#365]
When a query with before or after clause, the server returns ERROR response.
the code runs a SQL query with like condition `pstmt.setString( 4, "%urn:xmpp:sid:%" );`
but messages are stored without this xmlns.

```
2023.09.28 01:48:17 [36mDEBUG[m [message-archive-handler-84]: org.jivesoftware.openfire.archive.ConversationManager - Looking for ID of the message with stable/unique stanza ID 5EF5C3F5-5C89-465E-8731-EABDB79D64C8
2023.09.28 01:48:17 [36mDEBUG[m [message-archive-handler-84]: org.jivesoftware.openfire.archive.ConversationManager - Unable to find ID of the message with stable/unique stanza ID 5EF5C3F5-5C89-465E-8731-EABDB79D64C8
2023.09.28 01:48:17 [36mDEBUG[m [message-archive-handler-84]: org.jivesoftware.openfire.archive.ConversationManager - Fallback mechanism: parse value as old database identifier: '5EF5C3F5-5C89-465E-8731-EABDB79D64C8'
2023.09.28 01:48:17 [36mDEBUG[m [message-archive-handler-84]: org.jivesoftware.openfire.archive.ConversationManager - Fallback failed: value cannot be parsed as the old database identifier.
2023.09.28 01:48:17 [1;31mERROR[m [message-archive-handler-84]: com.reucon.openfire.plugin.archive.xep0313.IQQueryHandler - An exception has occurred while retrieving messages: 
java.lang.IllegalArgumentException: Unable to parse value '5EF5C3F5-5C89-465E-8731-EABDB79D64C8' as a database identifier.
	at org.jivesoftware.openfire.archive.ConversationManager.getMessageIdForStableId(ConversationManager.java:1108) ~[?:?]
	at com.reucon.openfire.plugin.archive.impl.JdbcPersistenceManager.findMessages(JdbcPersistenceManager.java:300) ~[?:?]
	at com.reucon.openfire.plugin.archive.xep0313.IQQueryHandler.retrieveMessages(IQQueryHandler.java:464) ~[?:?]
	at com.reucon.openfire.plugin.archive.xep0313.IQQueryHandler.lambda$handleIQ$2(IQQueryHandler.java:287) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by guusdk** [comment]
This problem seems to occur when interacting with personal archives (and maybe not when interacting with MUC archives). It is caused by an unrecognized SID being used (which in a last-ditch effort is attempted to being parsed as a database identifier).

This more or less duplicates issue #79

The proper way to handle unrecoginzed SIDs to return an `item-not-found` error.
