### ISSUE TITLE
Data too long for column 'stanza' at row 1

### ISSUE THREAD

**Issue by ptahchiev** [igniterealtime/openfire-monitoring-plugin#375]
Hello,

I'm using:
Openfire 4.7.5, build ee4395e
Monitoring service: 2.5.0

I see some of my messages are not sent and I checked the Openfire logs and I see this:
```
2024.02.28 16:52:18 TRACE [httpbind-worker-4]: org.jivesoftware.openfire.archive.ConversationManager - Processing message from date 2024-02-28T16:52:18.978+0200...
2024.02.28 16:52:18 TRACE [httpbind-worker-4]: org.jivesoftware.openfire.archive.ConversationManager - Done processing message from date 2024-02-28T16:52:18.978+0200.
2024.02.28 16:52:19 ERROR [archive-service-worker-3]: org.jivesoftware.openfire.archive.ConversationManager - Unable to archive message data!
java.sql.BatchUpdateException: Data truncation: Data too long for column 'stanza' at row 1
    at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
    at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?]
    at com.mysql.cj.util.Util.handleNewInstance(Util.java:192) ~[mysql-connector-j-8.0.32.jar:8.0.32]
    at com.mysql.cj.util.Util.getInstance(Util.java:167) ~[mysql-connector-j-8.0.32.jar:8.0.32]
    at com.mysql.cj.util.Util.getInstance(Util.java:174) ~[mysql-connector-j-8.0.32.jar:8.0.32]
    at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224) ~[mysql-connector-j-8.0.32.jar:8.0.32]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchWithMultiValuesClause(ClientPreparedStatement.java:718) ~[mysql-connector-j-8.0.32.jar:8.0.32]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:409) ~[mysql-connector-j-8.0.32.jar:8.0.32]
    at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:795) ~[mysql-connector-j-8.0.32.jar:8.0.32]
    at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:241) ~[commons-dbcp2-2.9.0.jar:2.9.0]
    at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:241) ~[commons-dbcp2-2.9.0.jar:2.9.0]
    at org.jivesoftware.openfire.archive.ConversationManager$MessageArchivingRunnable.store(ConversationManager.java:1335) [monitoring-2.5.0.jar:?]
    at org.jivesoftware.openfire.archive.Archiver.run(Archiver.java:154) [xmppserver-4.7.5.jar:4.7.5]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
    at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'stanza' at row 1
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[mysql-connector-j-8.0.32.jar:8.0.32]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[mysql-connector-j-8.0.32.jar:8.0.32]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061) ~[mysql-connector-j-8.0.32.jar:8.0.32]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009) ~[mysql-connector-j-8.0.32.jar:8.0.32]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320) ~[mysql-connector-j-8.0.32.jar:8.0.32]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchWithMultiValuesClause(ClientPreparedStatement.java:679) ~[mysql-connector-j-8.0.32.jar:8.0.32]
    ... 11 more
2024.02.28 16:52:19 TRACE [archive-service-worker-3]: org.jivesoftware.openfire.archive.Archiver - Stored all produced work in the database. Work size: 1
2024.02.28 16:52:19 TRACE [archive-service-worker-2]: org.jivesoftware.openfire.archive.Archiver - Stored all produced work in the database. Work size: 1
```

**Comment by ptahchiev** [comment]
I'm really sorry - my bad I was sending a base64 encoded picture in the message and that made the stanza too big.
