### ISSUE TITLE
openfire 4.10: java.lang.NoSuchMethodError:  org.jivesoftware.openfire.muc.MUCRoom.getAffiliation(org.xmpp.packet.JID)

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-monitoring-plugin#392]
Logged whilst trying to use openfire 4.10
```
2024.10.18 15:56:10 ESC[1;31mERRORESC[m [socket_c2s-thread-4]: org.jivesoftware.openfire.nio.NettyConnectionHandler - Closing connection on /2a05:d014:12f0:9703:e77d:1950:a7d4:cb0d:5222
--/2a10:3781:420d:1:c9a3:467:be50:1f29:38170 due to error while processing message: <iq type="set" id="s1VmF5tBve4H" from="guus.der.kinderen@igniterealtime.org/Conversations.-fgD" to="x
mppnetworkgraph@conference.igniterealtime.org" xmlns="jabber:client"><query queryid="c3hjur06uj" xmlns="urn:xmpp:mam:2"><x type="submit" xmlns="jabber:x:data"><field var="FORM_TYPE" typ
e="hidden"><value>urn:xmpp:mam:2</value></field><field var="start"><value>2024-09-23T19:40:31.074Z</value></field><field var="end"><value>2024-10-13T15:56:11.606Z</value></field></x><se
t xmlns="http://jabber.org/protocol/rsm"><before/><max>50</max></set></query></iq>
java.lang.NoSuchMethodError: 'org.jivesoftware.openfire.muc.MUCRole$Affiliation org.jivesoftware.openfire.muc.MUCRoom.getAffiliation(org.xmpp.packet.JID)'
        at com.reucon.openfire.plugin.archive.xep0313.IQQueryHandler.handleIQ(IQQueryHandler.java:181) ~[?:?]
        at org.jivesoftware.openfire.muc.spi.MultiUserChatServiceImpl.process(MultiUserChatServiceImpl.java:504) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
        at org.jivesoftware.openfire.muc.spi.MultiUserChatServiceImpl.processPacket(MultiUserChatServiceImpl.java:375) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
        at org.jivesoftware.openfire.component.InternalComponentManager$RoutableComponents.process(InternalComponentManager.java:864) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
        at org.jivesoftware.openfire.spi.RoutingTableImpl.routeToComponent(RoutingTableImpl.java:516) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
        at org.jivesoftware.openfire.spi.RoutingTableImpl.routePacket(RoutingTableImpl.java:331) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
        at org.jivesoftware.openfire.IQRouter.handle(IQRouter.java:352) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
        at org.jivesoftware.openfire.IQRouter.route(IQRouter.java:106) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
...
```

**Comment by guusdk** [comment]
This presumably was with version 2.6.0 of the plugin.
