### ISSUE TITLE
Restarting the monitoring plug in causes existing active conversations not to be displayed

### ISSUE THREAD

**Issue by mjones216** [igniterealtime/openfire-monitoring-plugin#397]
If you restart the monitoring service on all nodes when you go back to Server > Archiving > Conversations, previous active conversations are not displayed and continue not to be logged when new messages on existing chats are sent.  New chats are registered but only on the senior node.  Also noted that the active conversation count on refresh displayed -1 before changing to 0.

Issue exists on the following versions: 
**Monitoring Service v2.6.1 with Openfire 4.9, clustered **
**Monitoring Service v2.7.0 with Openfire 4.10.0, clustered ** 

log file error from 4.10.0
```
[1;31mERROR[m [Jetty-QTP-AdminConsole-153]: org.jivesoftware.openfire.plugin.util.cache.ClusteredCacheFactory - Failed to execute cluster task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: class org.jivesoftware.openfire.plugin.MonitoringPlugin cannot be cast to class org.jivesoftware.openfire.plugin.MonitoringPlugin (org.jivesoftware.openfire.plugin.MonitoringPlugin is in unnamed module of loader org.jivesoftware.openfire.container.PluginClassLoader @4639ab62; org.jivesoftware.openfire.plugin.MonitoringPlugin is in unnamed module of loader org.jivesoftware.openfire.container.PluginClassLoader @3d013b44)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.hazelcast.executor.impl.DistributedExecutorService$Processor.run(DistributedExecutorService.java:288) ~[?:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:220) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[?:?]
	at com.hazelcast.internal.util.executor.PoolExecutorThreadFactory$ManagedThread.executeRun(PoolExecutorThreadFactory.java:74) ~[?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) ~[?:?]
Caused by: java.lang.ClassCastException: class org.jivesoftware.openfire.plugin.MonitoringPlugin cannot be cast to class org.jivesoftware.openfire.plugin.MonitoringPlugin (org.jivesoftware.openfire.plugin.MonitoringPlugin is in unnamed module of loader org.jivesoftware.openfire.container.PluginClassLoader @4639ab62; org.jivesoftware.openfire.plugin.MonitoringPlugin is in unnamed module of loader org.jivesoftware.openfire.container.PluginClassLoader @3d013b44)
	at org.jivesoftware.openfire.archive.cluster.GetConversationsTask.run(GetConversationsTask.java:61) ~[monitoring-2.7.0-SNAPSHOT.jar:?]
	at org.jivesoftware.openfire.plugin.util.cache.ClusteredCacheFactory$CallableTask.call(ClusteredCacheFactory.java:656) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at com.hazelcast.executor.impl.DistributedExecutorService$Processor.run(DistributedExecutorService.java:286) ~[?:?]
```

**Comment by iarwen** [comment]
On the latest version 5.0.1, I met the same issue.
