### ISSUE TITLE
SQL Server incompatibility

### ISSUE THREAD

**Issue by mightymop** [igniterealtime/openfire-monitoring-plugin#47]
I've found that Exception in the logs with Version 1.8.0
(Openfire 4.4 on SQL Server)
SQL Server does not know "LIMIT" ... it uses "TOP" or "OFFSET"
```
2019.07.10 08:21:45 ERROR [message-archive-handler-93]: com.reucon.openfire.plugin.archive.impl.MucMamPersistenceManager - SQL failure during MAM-MUC:
java.sql.SQLException: Incorrect syntax near 'LIMIT'.
        at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372) ~[jtds-1.3.1.jar:1.3.1]
        at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988) ~[jtds-1.3.1.jar:1.3.1]
        at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421) ~[jtds-1.3.1.jar:1.3.1]
        at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671) ~[jtds-1.3.1.jar:1.3.1]
        at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQLQuery(JtdsStatement.java:505) ~[jtds-1.3.1.jar:1.3.1]
        at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.executeQuery(JtdsPreparedStatement.java:1029) ~[jtds-1.3.1.jar:1.3.1]
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.6.0.jar:2.6.0]
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.6.0.jar:2.6.0]
        at com.reucon.openfire.plugin.archive.impl.MucMamPersistenceManager.getArchivedMessages(MucMamPersistenceManager.java:143) ~[?:?]
        at com.reucon.openfire.plugin.archive.impl.MucMamPersistenceManager.findMessages(MucMamPersistenceManager.java:103) ~[?:?]
        at com.reucon.openfire.plugin.archive.xep0313.IQQueryHandler.retrieveMessages(IQQueryHandler.java:326) ~[?:?]
        at com.reucon.openfire.plugin.archive.xep0313.IQQueryHandler.lambda$handleIQ$0(IQQueryHandler.java:205) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

**Comment by GregDThomas** [comment]
Can you confirm which databas you are seeing this with?

**Comment by mightymop** [comment]
I am using sql server 2017 enterprise linux or what do you wanted to know?

**Comment by GregDThomas** [comment]
No, that's we needed to know (it's also what I suspected, but good to get it confirmed).

**Comment by mightymop** [comment]
Any news on this? it spams my error log ^^

**Comment by guusdk** [comment]
Please remember that we're all volunteers with limited availability. If there's an urgency for you to have this fixed, please consider supplying a fix yourself.

**Comment by mightymop** [comment]
fixed with https://github.com/igniterealtime/openfire-monitoring-plugin/pull/57

**Comment by guusdk** [comment]
The fix was merged, and will be part of the next release. Thanks for your help!
